
package ws.tata.com.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Tue Apr 11 19:46:56 IST 2017
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "getNameResponse", namespace = "http://com.tata.ws/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getNameResponse", namespace = "http://com.tata.ws/")

public class GetNameResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

